config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'landing#index'
  # address for the gameover screen. right now it's just {host}/gameover
  get 'gameover', to: 'gameover#index'
  resources :games, only: [:show]
end

app/models/application_record.rb
# frozen_string_literal: true

# stub class for application record
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    # return the actual user or a guest
    logged_in_user || guest_user
  end

  def logged_in_user
    # return the actual logged in user if they exist
    defined?(super) ? super : nil
  end

  private

  def guest_user
    # if the guest session is exists, then return that user
    return User.find(session[:guest_user_id]) if session[:guest_user_id].nil? == false

    # else, create a new user, set that user's session id as the session id, and return that user
    guest_id = create_guest_user.id
    session[:guest_user_id] = guest_id
    User.find(guest_id)
  end

  def create_guest_user
    guest_user = User.create(guest: true, password: guest_user_password, email: guest_user_email)
    guest_user.save(validate: false)
    guest_user
  end

  # creates a guest user email with in the form Time.now.to_i}
  def guest_user_email
    "guest_#{Time.now.to_i}#{rand(99)}@example.com"
  end

  # creates an alphanumeric string
  def guest_user_password
    password_length = 6
    (0...password_length).map { rand(65..90).chr }.join
  end
end

app/controllers/gameover_controller.rb
class GameoverController < ApplicationController
  def index
    @game = 1 # TODO: expand game logic when records are necessary
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

require 'device_detector'
class GamesController < ApplicationController
  def show
    # dummy object or Game.find(params[:id])
  end

  # Determines the correct user prompt based on device type, helper method to be used in view
  #
  # @return [String] message detailing appropriate user instructions
  def user_prompt_controls
    #      postconditions
    #        The string is of one of three states:
    #         message for desktop-based
    #         message for tablet or phone based controls
    #         empty string for unrecognized browser types

    device = DeviceDetector.new(request.user_agent).device_type
    # (a "phablet" is a marketing term for a larger smart phone)
    if %w[smartphone tablet phablet].include?(device)
      'Tap to Turn'
    elsif device == 'desktop'
      'Use Arrow Keys to Turn'
    else
      ''
    end
  end
  helper_method :user_prompt_controls
end

app/controllers/landing_controller.rb
# frozen_string_literal: true

# Controller for the landing page
class LandingController < ApplicationController
  def index
    @game = 1 # TODO: expand game logic when records are necessary
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper, currently stubbed
module ApplicationHelper
end

app/helpers/landing_helper.rb
# frozen_string_literal: true

# Stubbed helper module for the landing page
module LandingHelper
end

app/views/gameover/index.html.erb
<section class="scanlines font-arcade page-style">
    <h1 class="main-title">
      Game Over
  </h1>
    <%= render(PlayButtonComponent.new(label: "Play Again", path: game_path(@game))) %>
    </section>

app/views/games/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Light Cycles: Demo</title>
     </head>
  <body class="m-0 flex items-center justify-center min-h-screen bg-gray-700">
    <div class="min-h-screen bg-gray-700 flex items-center justify-center m-0">
        <div id="app" class="bg-black border-4 border-blue-500 p-4 w-fit h-fit">
           <!-- game mounts here -->
             <!-- control prompt overlays here -->
             <div class="control-prompt"><%=user_prompt_controls%></div>
         </div>
    </div>
    <script type="module">
      import "raycaster";
    </script>
  </body>
</html>

app/views/landing/index.html.erb
<section class="scanlines font-arcade page-style">
    <h1 class="glow-text main-title drop-shadow-neon">
    "Lite" Cycle
  </h1>
  <p class="text-xl sm:text-2xl text-pink-300 max-w-xl mb-8 drop-shadow">
    Race to Survive.
  </p>
  <%= render(PlayButtonComponent.new(label: "Play Now!", path: game_path(@game))) %>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RacingSnakesRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= tag.link rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" %>

  </head>
  <body class="bg-black text-pink-500 font-arcade">
    <%= yield %>
    </body>
</html>